---
title: "Project"
subtitle: "Stats 5405"
author: "Kevin Russell & Josh Moak"
format: html
title-block-style: plain
---

The following code adds 5 new columns to our data set, derived from current columns. 

```{r}
df <- read.csv("chess_games.csv")
df <- df[-which(df["turns"] <= 1), ]
```

```{r}
# Function to find white castle move
find_castle_move_white <- function(x) {
  chess_game <- x[11]
  moves <- unlist(strsplit(chess_game, " "))
  move_number <- 1
  white_castling_move <- NULL

  for (move in moves) {
    if (grepl("O-O|O-O-O", move)) {
      if (move_number %% 2 == 1) {
        white_castling_move <- ceiling(move_number / 2)
      }
    }
    move_number <- move_number + 1
  }
  if (is.null(white_castling_move)){
    return(0)
  }
  return(white_castling_move)
}

# Function to find black castle move
find_castle_move_black <- function(x) {
  chess_game <- x[11]
  moves <- unlist(strsplit(chess_game, " "))
  move_number <- 1
  black_castling_move <- NULL

  for (move in moves) {
    if (grepl("O-O|O-O-O", move)) {
      if (move_number %% 2 == 0) {
        black_castling_move <- (move_number / 2)
      }
    }
    move_number <- move_number + 1
  }
  if (is.null(black_castling_move)){
    return(0)
  }
  return(black_castling_move)
}

# Function to find white pawn push move
find_pawn_moves_white <- function(x) {
  chess_game <- x[11]
  moves <- unlist(strsplit(chess_game, " "))
  pawn_moves <- 0
  pattern <- "^[a-h][1-8x]"
  move_number <- 1

  for (move in moves) {
    if (grepl(pattern, move)) {
      if (move_number %% 2 == 1) {
        pawn_moves <- pawn_moves + 1
      }
    }
    move_number <- move_number + 1
  }
  return(pawn_moves)
}


# Function to find black pawn push move
find_pawn_moves_black <- function(x) {
  chess_game <- x[11]
  moves <- unlist(strsplit(chess_game, " "))
  pawn_moves <- 0
  pattern <- "^[a-h][1-8x]"
  move_number <- 1

  for (move in moves) {
    if (grepl(pattern, move)) {
      if (move_number %% 2 == 0) {
        pawn_moves <- pawn_moves + 1
      }
    }
    move_number <- move_number + 1
  }
  return(pawn_moves)
}

# Function to find game type
find_game_type <- function(x) {
  type_code <- x[6]
  
  moves <- unlist(strsplit(type_code, "+", fixed = TRUE))
  move <- as.numeric(moves[1])
  if (move <= 5){
    return("bullet")
  }
  else if (move <= 10){
    return("blitz")
  }
  else {return("rapid")}
  
}
```


```{r}

df$white_castle <- apply(df, 1, FUN = find_castle_move_white)
df$black_castle <- apply(df, 1, FUN = find_castle_move_black)
df$white_pawn_moves <- apply(df, 1, FUN = find_pawn_moves_white)
df$black_pawn_moves <- apply(df, 1, FUN = find_pawn_moves_black)
df$game_type <- apply(df, 1, FUN = find_game_type)


```

Now, we call each of our functions (takes a minute to run) on all rows of the data
```{r}

white_castle <- c()
for (i in seq(1:nrow(df))) {  
  white_castle <- c(white_castle, find_castle_move_white(i))
}

black_castle <- c()
for (i in seq(1:nrow(df))){
  black_castle <- c(black_castle, find_castle_move_black(i))
}

white_pawn <- c()
for (i in seq(1:nrow(df))) {  
  white_pawn <- c(white_pawn, find_pawn_moves_white(i))
}

black_pawn <- c()
for (i in seq(1:nrow(df))) {  
  black_pawn <- c(black_pawn, find_pawn_moves_black(i))
}

game_types <- c()
for (i in seq(1:nrow(df))){
  game_types <- c(game_types, find_game_type(i))
}


```

Finally, we add the new derived/engineered columns to our data frame
```{r}
df["white_castle"] <- white_castle
df["black_castle"] <- black_castle
df["white_pawn_moves"] <- white_pawn
df["black_pawn_moves"] <- black_pawn
df["game_type"] <- game_types
```




